### ISSUE TITLE
go run hpfix.go hpfix.go:10:2: no required module provides package github.com/davecgh/go-spew/spew: go.mod file not found in current directory or any parent directory; see 'go help modules'

### ISSUE THREAD

**Issue by bitt69** [Isanderthul/T120bsodFix#1]
Hi there!
I'm stuck with Your tutorial how to fix Blue screen on installing go-spew with hpfix.go file. I tried to install it manually but there's no longer go get, there's go install, and the result is:
go install github.com/davecgh/go-spew/spew@latest
package github.com/davecgh/go-spew/spew is not a main package

i run hpfix.go file:
go run hpfix.go
hpfix.go:10:2: no required module provides package github.com/davecgh/go-spew/spew: go.mod file not found in current directory or any parent directory; see 'go help modules'

Can you help me fix this, and skip further with your tutorial to fix my T520 blue screen?
i succesfully cloned USB sticks, and stuck with above issue.

**Comment by Isanderthul** [comment]
OK I see what you mean, I am going to try get this working again on my mac, then I will be able to answer the question. Please be patient, trying to work this out too.

**Comment by Isanderthul** [comment]
I have added a go.mod and a go.sum
Hopefully that helps fix it.
I will have to open my printer to see what the firmware I need is, because I could not find `amperexl_pr_AXP2CN2022AR_secure_signed_rbx.ful` on the RU website. 
So now the repo has two firmwares, and I am not sure which one is the right one...

I think my mac tried to update the printer fw again, and my printer has returned to having a bsod 😠 , so when I get my printer working again I can clarify which fw I needed ( amperexl_pr_AXP2CN2022AR_secure_signed_rbx or amperexl_pr_AXP2CN1829BR_secure_signed_rbx.ful )

**Comment by Isanderthul** [comment]
I was thinking that it might be good to have one of those usb with the switch to make it read only, I will see if I can try that to prevent future firmware update attempts causing another bsod.

**Comment by bitt69** [comment]
Thank You for your support!
I put the go.mod and go.sum files in the same directory as hpfix.go file, then run hpfix.go and then dd the result file into flash drive and my T520 works now!!!!

**Comment by Isanderthul** [comment]
Awesome news!
